apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-app
  namespace: netology
  labels:
    app: nginx-test-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test-app 
  template:
    metadata:
      labels:
        app: nginx-test-app
    spec:
      containers:
      - name: nginx-test-app
        image: registry.gitlab.com/devops-netology-group/devops_diplom/app:1.0.0
        ports:
        - containerPort: 80